### ISSUE TITLE
数据集不存在

### ISSUE THREAD

**Issue by Echo0117** [jievince/rdf-converter#2]
Hi, 请问一下清洗好的数据集还有吗，链接点进去是这样的：

![image](https://user-images.githubusercontent.com/54064209/104280906-980b7b80-54e7-11eb-9a6d-c36b2b43e2a3.png)

谢谢啦~

**Comment by jievince** [comment]
不好意思， 清洗好的数据已经删除掉了， 因为一直放在oss上要收费的

**Comment by Echo0117** [comment]
> 不好意思， 清洗好的数据已经删除掉了， 因为一直放在oss上要收费的

嗯嗯好哒，谢谢你~

**Comment by Echo0117** [comment]
Hi,

我想问一下你现在还在 vesoft 工作吗~ 因为我在使用 nebula 数据库的时候还有些问题，不知道能不能请教一下你呀~
我现在的工作是 NLP 算法工程师， 要是方便的话，可以加一下微信方便交流的，我微信号/手机号是：18674163303

谢谢~

jie.wang <notifications@github.com> 于2021年1月12日周二 下午3:22写道：

**Comment by ghost** [comment]
能否放完全去重后的数据在云盘或者其他地方下供下载，emmmm。🙏

**Comment by wey-gu** [comment]
@jievince 我/你可以把去重数据放到 Kaggle 上么？

**Comment by jievince** [comment]
> @jievince 我/你可以把去重数据放到 Kaggle 上么？

ok的
